//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ildss
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public Directory()
        {
            this.Files = new HashSet<File>();
        }
    
        public int DirectoryId { get; set; }
        public string path { get; set; }
    
        public virtual ICollection<File> Files { get; set; }
    }
}
