//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ildss
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int FileId { get; set; }
        public string path { get; set; }
        public string hash { get; set; }
        public int DirectoryDirectoryId { get; set; }
    
        public virtual Directory Directory { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
